Error fix from enabling Clang thread-safety checks.
Parent bug: b/353324127. Enabling `thread-safety-reference-return`
to allow developers to utilize Clang thread safety guardrails
(GUARDED_BY, REQUIRES, EXCLUDES).

Errors (sample; 10 total):

frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp:2676:55:
error: returning variable 'mDisplays' by reference requires holding
mutex 'mStateLock' exclusively [-Werror,-Wthread-safety-reference-return]

 frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp:6027:65:
 error: returning variable 'mPhysicalDisplays' by reference requires
 holding mutex 'mStateLock' exclusively
 [-Werror,-Wthread-safety-reference-return]

Fix: return by value, add REQUIRES attribute to each function, or
remove GUARDED_BY attribute.

This fix removes the GUARDED_BY attribute in order to avoid changing
functionality. If this is not desired, please respond with concerns
or preferred fix.

Change-Id: I9c41e5fa655c22798f75a719f765c76a0729b378
Bug: 354740314
Test: make