Disable Clang thread-safety checks in surfaceflinger unit tests
Parent bug: b/353324127. Enabling `thread-safety-reference-return`
to allow developers to utilize Clang thread safety guardrails.

The surfaceflinger unittest suite currently does not untilize mutex
locks when calling required thread-safe variables.

Example error:
frameworks/native/services/surfaceflinger/tests/unittests/TestableScheduler.h:133:52
error: returning variable 'mAttachedChoreographers' by reference
requires holding mutex 'mChoreographerLock' exclusively
[-Wthread-safety-reference-return]

Disabling the Clang thread-safety-reference-return error to avoid
changing functionality. If this is not desired, please respond with
concerns or preferred fix.

Bug: 354740314
Test: make

Change-Id: I95793ab942207660ea8e49cfd50d089e956a7ada